#!/bin/sh

set -v
set -e

rm -rf node_modules/
rm -rf npm-shrinkwrap.json
npm install
npm test
make man
npm shrinkwrap
npm pack
ls -hl *.tgz
mv *.tgz ../

: check upload size is ~5M
: git hf release finish x.y.z
: npm publish (from master branch?)
: npm cache clear
: npm install -g strong-cli
: SLC=`which slc` npm test
