#!/bin/sh

set -v
set -e

git clean -x -d
npm install
npm test
make man
npm pack
ls -hl *.tgz
mv *.tgz ../

: check upload size is ~5M
: git hf release finish x.y.z
: npm publish "(from master branch?)"
: npm cache clear
: npm install -g strongloop
: SLC=`which slc` npm test
